;
; INTERRUPT-HANDLING ROUTINE
; COMPLEMENTS LEDS AT EACH INTERRUPT.
;
DOINT   PHA                 ; SAVE ACCUMULATOR
        LDA     PORT1A      ; GET PORT FOR COMPLEMENTING
        EOR     MASKA       ; COMPLEMENT NECESSARY BITS
        STA     PORT1A      ; STORE COMPLEMENTED CONTENTS
        LDA     PORT1B      ; DO SAME WITH PORT1B
        EOR     MASKB
        STA     PORT1B
        LDA     T1LL        ; CLEAR INTERRUPT BIT IN VIA
        PLA                 ; RESTORE ACCUMULATOR
        RTI                 ; DONE, RESUME PROGRAM