        .CR     65C02
        .TF     spinner.hex,INT
        .LF     spinner.list
;
; SPINNER IS A REACTION TIMING GAME USING '6502 GAMES' HARDWARE, AN LED CHASES
; AROUND THE LED CUBE AND YOU SHOULD TRY TO HIT THE CORRESPONDING BUTTON.
; BOARD SHOULD ; BE JUMPERED WITH VIA CHIPS AT THE ADDRESSES SPECIFIED BELOW.
; OTHER THAN THAT THE CODE IS SHOULD BE UNCHANGED FROM THE BOOK THOUGH THERE 
; WILL BE SOME DIFFERENCES DUE TO ASSEMBLER USED.
;
VIA1    .EQ     $4000       ; GAME BOARD (VIA #1)
VIA3    .EQ     $4C00       ; GAME BOARD (VIA #3)

        .OR     $8000
        .TA     $0000
BE6502  .IN     ../../common/CH06-Spinner/game.asm
;
; STORE CPU INITIALIZATION VECTORS AT THE END OF THE EEPROM.
;
        .NO     $FFFA,$FF
        .DA     BE6502      ; NMI VECTOR
        .DA     BE6502      ; RESET VECTOR
        .DA     BE6502      ; IRQ VECTOR