        .CR     6502
        .TF     getkey.hex,hex
        .LF     getkey.list
;
; FROM THE BOOK '6502 GAMES', EXPECTS THE SAME HARDWARE AS DECRIBED WITHIN IT.
; THIS PART WAS NOT MEANT TO BE RUN DIRECTLY, SO I'VE JUST KEPT THE ADDRESS
; DEFINITIONS GIVEN IN THAT CHAPTER.
;
VIA1    .EQ     $C000
VIA3    .EQ     $CC00

        .OR     $0100       ; NOTE: BOOK PLACES $0100 INSIDE STACK, MEANING
        .TA     $0100       ;  THAT ROUTINE MAY EASILY GET OVERWRITTEN.
        .IN     getkey_routine.asm